### PR TITLE
Fix implicit self warnings

### PR DESCRIPTION
**Pull request by liambutler-lawrence**
### Background
I'm on the iOS team at [TrueMotion](https://gotruemotion.com) and we have a client that has a no-warnings policy which includes 3rd party dependencies. We use RNCryptor in our SDK and so its warnings show up for our client.

### Changes
After cloning and opening the project, I saw no warnings. It turned out this was because the warnings I previously observed are new in Xcode 9: `CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF`. Therefore, I made two changes:

* Accepted Xcode's suggestion to update the project to recommended settings
* Fixed the 6 "implicit self reference in block" warnings by explicitly referencing self. Note that this doesn't actually affect memory management because `self` was already being explicitly referenced in each block.

### CODE REVIEW

**Comment by liambutler-lawrence** [comment]
@rnapier I promise this will be quick!

**Comment by rnapier** [comment]
Thanks @liambutler-lawrence.

**Comment by rnapier** [comment]
Please see Release 3.0.6 (and updated CocoaPods)

**Comment by liambutler-lawrence** [comment]
@rnapier Thank you for the quick response!

**Pull request merged**
